version: '3.9'

services: 
  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.2
    hostname: schema-registry
    container_name: schema-registry
    restart: always
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8084:8085

  schema-registry-ui:
    image: landoop/schema-registry-ui
    hostname: schema-ui
    container_name: schema-ui
    depends_on: 
      - schema-registry
    environment: 
      SCHEMAREGISTRY_URL: "http://schema-registry:8085"
    ports:
      - 8083:8000 

networks: 
  default:
    external: 
      name: kafka_playground
  

