FROM base/jdk11

LABEL maintainer="haekyu cho <haekyu.cho@nhn.com>"
LABEL title="zookeeper"
LABEL version="1.0"

# https://downloads.apache.org/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz

ARG USER=docker
ARG ZK_VERSION=3.6.2
ARG ZK_NAME=zookeeper-${VERSION}
ARG ZK_HOME=/opt/zookeeper
ARG ZK_CLIENT_PORT=2181

ENV PATH=$PATH:$ZK_HOME/bin \
    ZOO_LOG4J_PROP=INFO,CONSOLE \
    ZK_USER=${USER} \
    ZK_HOME=${ZK_HOME}

RUN wget -q "https://downloads.apache.org/zookeeper/${ZK_NAME}/${ZK_NAME}-bin.tar.gz" && \
    tar -zxf ${ZK_NAME}-bin.tar.gz && \
    mv apache-zookeeper-3.6.2-bin ${ZK_HOME}

# adding entrypoint and startup scripts
# COPY *.sh $ZK_HOME/bin/

# WORKDIR ${ZK_HOME}
# EXPOSE ${ZK_CLIENT_PORT} 2888 3888
# VOLUME ["${ZK_HOME}/data", "${ZK_HOME}/logs"]

# ENTRYPOINT ["entrypoint.sh"]
# CMD ["bootstrap.sh", "zkServer.sh", "start-foreground"]
